package com.main.tomcatSessions.dao;

import com.main.tomcatSessions.model.TomcatSessions;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TomcatSessionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    int insert(TomcatSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    int insertSelective(TomcatSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    TomcatSessions selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TomcatSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TomcatSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tomcat_sessions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TomcatSessions record);

    List<TomcatSessions> selectList(@Param("page") Integer page, @Param("limit") Integer limit, @Param("tomcatSessions") TomcatSessions tomcatSessions);

}