package com.main.webURL.model;

public class WebURL {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.protocol
     *
     * @mbg.generated
     */
    private String protocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.subdomain
     *
     * @mbg.generated
     */
    private String subdomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.suffix
     *
     * @mbg.generated
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.status_code
     *
     * @mbg.generated
     */
    private Integer statusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.encoding
     *
     * @mbg.generated
     */
    private String encoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.cookie
     *
     * @mbg.generated
     */
    private String cookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_url.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.id
     *
     * @return the value of web_url.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.id
     *
     * @param id the value for web_url.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.url
     *
     * @return the value of web_url.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.url
     *
     * @param url the value for web_url.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.host
     *
     * @return the value of web_url.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.host
     *
     * @param host the value for web_url.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.protocol
     *
     * @return the value of web_url.protocol
     *
     * @mbg.generated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.protocol
     *
     * @param protocol the value for web_url.protocol
     *
     * @mbg.generated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.subdomain
     *
     * @return the value of web_url.subdomain
     *
     * @mbg.generated
     */
    public String getSubdomain() {
        return subdomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.subdomain
     *
     * @param subdomain the value for web_url.subdomain
     *
     * @mbg.generated
     */
    public void setSubdomain(String subdomain) {
        this.subdomain = subdomain == null ? null : subdomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.domain
     *
     * @return the value of web_url.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.domain
     *
     * @param domain the value for web_url.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.suffix
     *
     * @return the value of web_url.suffix
     *
     * @mbg.generated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.suffix
     *
     * @param suffix the value for web_url.suffix
     *
     * @mbg.generated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.status_code
     *
     * @return the value of web_url.status_code
     *
     * @mbg.generated
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.status_code
     *
     * @param statusCode the value for web_url.status_code
     *
     * @mbg.generated
     */
    public void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.encoding
     *
     * @return the value of web_url.encoding
     *
     * @mbg.generated
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.encoding
     *
     * @param encoding the value for web_url.encoding
     *
     * @mbg.generated
     */
    public void setEncoding(String encoding) {
        this.encoding = encoding == null ? null : encoding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.cookie
     *
     * @return the value of web_url.cookie
     *
     * @mbg.generated
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.cookie
     *
     * @param cookie the value for web_url.cookie
     *
     * @mbg.generated
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.type
     *
     * @return the value of web_url.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.type
     *
     * @param type the value for web_url.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.title
     *
     * @return the value of web_url.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.title
     *
     * @param title the value for web_url.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_url.content
     *
     * @return the value of web_url.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_url.content
     *
     * @param content the value for web_url.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}