package com.main.user.dao;

import com.main.user.model.User;
import com.main.user.model.UserWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    UserWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    List<UserWithBLOBs> selectList(@Param("page") Integer page, @Param("limit") Integer limit, @Param("user") UserWithBLOBs user);

    UserWithBLOBs selectByAccountNumber(@Param("phoneNumber") long phoneNumber, @Param("mailbox") String mailbox);

    long count(UserWithBLOBs user);

    long countByLogin(@Param("phoneNumber") long phoneNumber, @Param("maibox") String maibox);

    int inserts(UserWithBLOBs user);

    int updates(UserWithBLOBs user);

    int deletes(String[] id);
}