package com.ceshi.dao;

import com.ceshi.model.ceshi;
import com.ceshi.model.ceshiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ceshiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    long countByExample(ceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    int deleteByExample(ceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    int insert(ceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    int insertSelective(ceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    List<ceshi> selectByExample(ceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ceshi record, @Param("example") ceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ceshi record, @Param("example") ceshiExample example);
}